DROP STREAM IF EXISTS FBNK_LD_SCHEDULE_101_MULTIVALUE DELETE TOPIC ;
DROP STREAM IF EXISTS FBNK_LD_SCHEDULE_101_MAPPED DELETE TOPIC ;
DROP STREAM IF EXISTS FBNK_LD_SCHEDULE_101 DELETE TOPIC ;

-- raw/ogg stream
CREATE OR REPLACE STREAM FBNK_LD_SCHEDULE_101 (
    ROWKEY STRING KEY,
    LOOKUP_KEY STRING,
    RECID STRING,
    `TABLE` STRING,
    SCN STRING,
    OP_TYPE STRING,
    OP_TS STRING,
    CURRENT_TS STRING,
    POS STRING,
    XID STRING,
    XMLRECORD STRING)
WITH (FORMAT='avro', KAFKA_TOPIC='FBNK_LD_SCHEDULE_101', PARTITIONS=2);
 
-- parse xml stream
CREATE OR REPLACE STREAM FBNK_LD_SCHEDULE_101_MAPPED  AS SELECT
  DATA.ROWKEY ROWKEY,
  DATA.LOOKUP_KEY LOOKUP_KEY,
  DATA.RECID RECID,  
  DATA.OP_TS OP_TS,  
  DATA.CURRENT_TS REP_TS,  
  TIMESTAMPTOSTRING(UNIX_TIMESTAMP(),'yyyy-MM-dd HH:mm:ss.SSSSSS') CURRENT_TS,
  DATA.`TABLE` TABLE_NAME,
  DATA.SCN COMMIT_SCN,  
  DATA.OP_TYPE COMMIT_ACTION
FROM FBNK_LD_SCHEDULE_101 DATA
EMIT CHANGES;
 
-- parse multivalue stream
CREATE OR REPLACE STREAM FBNK_LD_SCHEDULE_101_MULTIVALUE AS SELECT
  DATA.ROWKEY ROWKEY,
  DATA.LOOKUP_KEY LOOKUP_KEY,
  DATA.RECID RECID,
  DATA.OP_TS OP_TS,
  DATA.CURRENT_TS REP_TS,
  TIMESTAMPTOSTRING(UNIX_TIMESTAMP(), 'yyyy-MM-dd HH:mm:ss.SSSSSS') CURRENT_TS,
  DATA.TABLE_NAME TABLE_NAME,
  DATA.COMMIT_SCN COMMIT_SCN,
  DATA.COMMIT_ACTION COMMIT_ACTION
FROM FBNK_LD_SCHEDULE_101_MAPPED DATA
EMIT CHANGES;