CREATE STREAM FBNK_ACCOUNT_test (`TABLE` STRING, SCN STRING, OP_TYPE STRING, OP_TS STRING, CURRENT_TS STRING, POS STRING, XID STRING, ROWKEY STRING KEY, RECID STRING, XMLRECORD STRING, LOOKUP_KEY STRING) WITH (FORMAT='avro', KAFKA_TOPIC='FBNK_ACCOUNT_test',PARTITIONS=2);

drop stream FBNK_ACCOUNT_test delete topic ;